### ISSUE TITLE
Dotted Ouline On Track When Using Slider

### ISSUE THREAD

**Issue by DeanPoulin** [darlanrod/input-range-sass#13]
When I use the slider, it has a dotted outline. I see the rule in the SCSS for:

```scss
  &:focus {
    outline: 0;
    ...
  }
```
but I'm still seeing a dotted outline, at least in the latest Firefox.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/246410/41490708-4842aa3e-70c3-11e8-960d-0cc51883dd7f.png">
